// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKybyYvJ6UL44yqoKh2prEeF1MMqKaRNc',
    appId: '1:174271087333:web:13104f8de7a5a590f64a0c',
    messagingSenderId: '174271087333',
    projectId: 'open-munch-game',
    authDomain: 'open-munch-game.firebaseapp.com',
    storageBucket: 'open-munch-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfWHkIk2N0JODq-ulLV3cphCOfrwwjPkU',
    appId: '1:174271087333:android:9f61a2c930ee0752f64a0c',
    messagingSenderId: '174271087333',
    projectId: 'open-munch-game',
    storageBucket: 'open-munch-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmQ4P9gKJcaFr_qWWWqWCwrIASrXOFjVY',
    appId: '1:174271087333:ios:64813d247d00383af64a0c',
    messagingSenderId: '174271087333',
    projectId: 'open-munch-game',
    storageBucket: 'open-munch-game.appspot.com',
    iosClientId:
        '174271087333-6dj1lvibe9848c61ukdbc9okqa9qie3k.apps.googleusercontent.com',
    iosBundleId: 'com.leonhelm.open_munch_game',
  );
}
